'''Make clustering plots from id.txt files generated by clustering_xd.py'''

import numpy as np
from astropy.table import Table
from matplotlib import pyplot as plt


def plotting(dimensions, id_path, save_path):
    survey_data = Table.read('data_v3.txt', format='ascii.commented_header',
                             guess=False)

    if '2d' in dimensions:
        plots = Table.read('plots.txt', format='ascii.commented_header',
                           guess=False)
        for i in range(0, len(plots)):
            n_clusters = plots['n_clust'][i]
            algorithm = plots['clustering'][i]
            id_file_2d = load_id_file(n_clusters, algorithm, plots[i],
                                      dimensions, id_path)

    if '3d' in dimensions:
        plots_3d = Table.read('plots_3d.txt', format='ascii.commented_header',
                           guess=False)
        for j in range(0, len(plots)):
            n_clusters = plots_3d['n_clust'][j]
            algorithm = plots_3d['clustering'][j]
            id_file_3d = load_id_file(n_clusters, algorithm, plots_3d[j],
                                      dimensions, id_path)
    return()


def load_id_file(n_clust, clustering, bands, dim, path):
    if '2d' in dim:
        id_file_name = 'id_{}_{}cl_{}-{}vs{}-{}.txt'.format(clustering,
                                                            n_clust, bands[0],
                                                            bands[1], bands[2],
                                                            bands[3])
    if '3d' in dim:
        id_file_name = 'id_{}_{}cl_{}-{}vs{}-{}.txt'.format(clustering,
                                                            n_clust, bands[0],
                                                            bands[1], bands[2],
                                                            bands[3], bands[4],
                                                            bands[5])
    id_file_path = 'C:\\Users\\Owner\\Documents\\GitHub\\m83_clustering\\results\\{}\\{}'.format(path, id_file_name)
    id_file = Table.read(id_file_path, format='ascii.commented_header',
                         guess=False)
    return(id_file)


def load_2d_cluster_data():
    return(colour_data)


def load_3d_cluster_data():
    return(colour_data)


def 2d_plots():
    return()


def 3d_plots():
    return()
